- client/src/types/enums/sampleEnum.tsx
- client/src/types/interfaces/sampleInterface.tsx
- client/src/types/types/sampleType.tsx
- server/types/enums/sampleEnum.tsx
- server/types/interfaces/sampleInterface.tsx
- server/types/types/sampleType.tsx
1. Added directories for types to be used in the project, including those for custom types, enums, and interfaces.
To add separate folders to organize any custom types made for the project
The [scrimba on TypeScript](https://scrimba.com/learn/typescript/file-organisation-co0e34560ade9a97d96379cc3) said keeping custom typings in their own separate files was good practice for projects. We may or may not use this, but figured it wouldn't hurt to add.
Closes #006
> feat(added-types-directories): Added directories for types, enums, and interfaces

- client/index.html
- client/src/App.tsx
- client/src/pages/SubscribePage.css
- client/src/pages/SubscribePage.tsx
1. Created the initial layout of the subscribe page
2. Added the form data and store it via useState
The user can now fill out the form and get that information stored into a variable
User can now notify developer the type and frequency of subscription
Closes #18
> feat(subscribe page): Created the initial subscribe page layout

- client/src/App.tsx
- client/src/components/StaffDisplay/StaffCard.css
- client/src/components/StaffDisplay/StaffCard.tsx
- client/src/pages/StaffPage.css
- client/src/pages/StaffPage.tsx
- client/src/test/StaffData.tsx
- client/src/types/interfaces/Staff.tsx
1. Created Staff Card component and Staff data type
2. Created Staff page
3. Created dummy data for staff cards
4. Added basic css to match overall scheme
Implement a necessary page, and make it easy for quick additions or changes
Closes #017
> feat: implement staff page and necessary components

- client/.env.sample
- client/.gitignore
- client/src/App.tsx
- client/src/pages/ConfirmResetPasswordPage.tsx
- client/src/pages/LoginPage.tsx
- client/src/pages/RegisterPage.tsx
- client/src/pages/ResetPasswordPage.tsx
- server/.env.sample
- server/config/db.ts
- server/config/sampleConfig.ts
- server/models/User.ts
- server/models/sampleModel.ts
- server/routes/passwordResetRoute.ts
- server/routes/sampleRoute.ts
1. Updated .env.sample and several files throughout client and server to reflect DB migrations changes as well as .env usage updates
To refactor the app to use .env variables more liberally and to update .env.sample for the movement of the MongoDB from Dawid to the group account
Refactoring the API calls to use .env variables makes changing hosting for the server and client much easier
Dawid gave a thorough rundown of what was needed to use the server on the new MongoDB account
Closes #026
> refactor(env-usage): Updated .env.sample files to reflect DB migration, added .env usage in client

- client/package-lock.json
- client/package.json
- client/src/components/Navbar/Navbar.css
- client/src/components/Navbar/Navbar.tsx
1. Changed CSS for navbar to match figma design
2. added open weather api to get geolocation weather
3. put open weather api key in .env file
Update navbar
Open weather api
> Navbar updates

- client/src/App.tsx
- client/src/components/Navbar/Navbar.tsx
- client/src/components/StaffDisplay/StaffCard.css
- client/src/components/StaffDisplay/StaffCard.tsx
- client/src/pages/NewsPage.css
- client/src/pages/NewsPage.tsx
- client/src/pages/NewsSubPage.tsx
- client/src/pages/StaffPage.css
- client/src/pages/StaffPage.tsx
1. Added main news page
2. Created template for news sub pages
3. Added routing for the pages, and updated navbar to reflect changes
4. Small staff page fixes
Major implementation requirement
Two similar components, one for main, and one for sub pages. Share CSS file
Closes #030
> Feat(implementation): create news page and components

- server/models/Article.ts
- server/package-lock.json
- server/routes/articleRoute.ts
- server/routes/articlesRoute.ts
- server/server.ts
- server/types/interfaces/Article.ts
- server/types/interfaces/ArticleImage.ts
- server/types/types/ArticleTag.ts
- server/types/types/SportsArticleTag.ts
1. Added backend Article Types
2. Added API get routes for articles
The front end can now pull articles from the DB.
Implement a route which can allow access to either all articles or just by ID
There wasn't a research stage because I was already familiar with the technologies involved.
Closes Article API Route #40
> feat: Added Articles Route to backend

- client/.env.sample
- client/src/App.tsx
- client/src/components/ArticleCarousel.css
- client/src/components/ArticleCarousel.tsx
- client/src/components/ArticleThumbnails/ArticleThumbnail.css
- client/src/components/ArticleThumbnails/ArticleThumbnail.tsx
- client/src/components/BreakingNews/HeadlineBulletPoints.css
- client/src/components/BreakingNews/HeadlineColumn.css
- client/src/contexts/UserContext.tsx
- client/src/hooks/useArticleCarouselState.tsx
- client/src/pages/ArticlePage.tsx
- client/src/pages/BreakingNews.tsx
- client/src/types/types/ArticleTag.tsx
- client/src/utils/titleCase.ts
- server/config/db.ts
- server/models/Article.ts
- server/package-lock.json
- server/package.json
- server/routes/articleRoute.ts
- server/routes/articlesRoute.ts
- server/routes/authRoute.ts
- server/routes/business.ts
- server/routes/userRoute.ts
- server/types/types/ArticleTag.ts
1. Added a Headline Article Tag to use for choosing which articles to display at the top of the Breaking News page
2. Updated articles get endpoint on server to pull Breaking News by time posted
3. Refactored ArticleThumbnail component and child components to account for past Pull Requests changing how it looks
4. Added logic to pull Headline and Breaking News articles and display them on the Breaking News page
5. Made a new hook and added new logic to make ArticleCarousel work as intended
To get the BreakingNews page and ArticleCarousel component looking and working as intended for the MVP. Refactored article get endpoint on server to also pull Breaking News article based on recency of when they were posted, to expand the amount of articles posted to the BreakingNews page.
Refactoring …
> feat(breaking-news): Added logic to display appropriate articles on Breaking News/Home page

- server/vercel.json
1. Added configuration for cors in vercel.json in server
Configure cors for server deployment on vercel
> fix(cors-config): Configured Cors for Vercel Deployment

- server/vercel.json
1. Fixed headers formatting in vercel.json
To fix schema validation error from vercel deployment
> fix(vercel-json): Reformatted headers in headers to be an array

- server/vercel.json
1. Removed rewrites and headers options
2. Reconfigured routes option
To avoid cors issues on client
> fix(vercel-json): Trying Routes Option Over Rewrites and Headers

- server/vercel.json
1. Removed routes options
2. Added back rewrites and headers, added more objects to headers in headers key
To try and resolve cors issues with deployment
> fix(vercel-json): Removed Routes, Added Rewrites and Headers Back

- server/server.ts
1. Added object to configure cors on config call in server
2. Added get root endpoint to indicate the server is running
To try to resolve cors issues with server deployment
> fix(cors-config): Added Cors Config Object to Cors Config Call on Server

- server/server.ts
1. Added module export of express app on server
To try and accommodate Vercel's serverless functions and resolve cors issue
> fix(server-export): Added module.exports of express app on server

- client/README.md
1. Updated README in the client side of the application to document the various pages
Provide a concise overview of the purpose of the application and its parts
Closes #071
> feat(README): added readme documentation for the client side of the application

- crawler/cron.sh
- crawler/newsscraper/pipelines.py
- crawler/newsscraper/settings.py
- crawler/newsscraper/spiders/modbee.py
1. Added Cron to Crawler
2. Fixed duplicate articles going to mongo
_Describe the problem or feature._
implement #53 
_How does this change address the problem?_
Add cron file to schedule crawling.
_Describe the research stage_
none I had recently used cron
Closes #53
> feat: Crawler Cron

- client/src/App.css
- client/src/App.tsx
- client/src/components/Navbar/Navbar.css
- client/src/contexts/UserContext.tsx
- client/src/index.css
- client/src/pages/Authentication/ConfirmResetPasswordPage.tsx
- client/src/pages/Authentication/LoginPage.tsx
- client/src/pages/BusinessPanel/BusinessSettings.tsx
- client/src/utils/permissionsUtils.tsx
- server/email/emailService.ts
- server/routes/authRoute.ts
1. Fixed overlap bug with Navbar, increasing its z-index to prevent overlap
2. Fixed various styling errors
3. Fixed permissions for settings page on BusinessPanel
4. Added useEffect in userContext to persist user's login when a valid access_token is present
5. Refactored email service on service to be wrapped in async promise called with await to account for Vercel's lack of streaming response support
To address a number of bugs before presentation
Read a [stackoverflow post](https://stackoverflow.com/questions/65631481/nodemailer-in-vercel-not-sending-email-in-production) on why nodemailer doesn't work out of the box on Vercel and how to fix it
Closes #081
Closes #083
Closes #084
Closes #085
> fix: Fixed Navbar, Permissions, Session Persistence, Email, and Styling Errors/Bugs

- crawler/README.md
> feat: readme for crawler

- server/README.md
1. Updates server documentation to account for comment and comment notification endpoints 
To round out server documentation
Closes #097
> Update Server README.md

- cron/README.md
1. Updated cron documentation to mention comment notification service
To round out cron documentation in README
Closes #099
> Update Cron README.md

- server/README.md
1. Edited usage paragraph for reading clarity
2. Edited several endpoint's paragraphs for usage and reading clarity
To make a clarity quick fix for the server's documentation
> fix: Edited Server README for Reading Clarity
